language: php

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=sqlite
      php: 7.0
    - env: DBTYPE=sqlite
      php: 7.1
    - env: DBTYPE=sqlite
      php: 7.2
    - env: DBTYPE=mysql
      php: 7.2

before_script:
  - bash ./build/travis/before_script.sh

script:
  - bash ./build/travis/script.sh
